### ISSUE TITLE
how to plot modes

### ISSUE THREAD

**Issue by joamatab** [DerekK88/PICwriter#22]
Derek,

How do you produce the mode profile plots in the docs?

https://picwriter.readthedocs.io/en/latest/picsim-documentation.html

**Comment by joamatab** [comment]
I run the waveguide mode example but the TE modes looks different 

![image](https://user-images.githubusercontent.com/4514346/74549855-3e7c8480-4f05-11ea-967d-3d81b86b3f18.png)

**Comment by DerekK88** [comment]
This issue (which I was able to reproduce) was a result of geometric objects being added that span beyond the simulation domain.  Since there are periodic boundary conditions, they wrap around to the other side and can unintentionally overlap with other structures.  I have fixed this issue in 2a67b8a and confirmed that it now works on python 3.7 and with the latest pymeep.  Apologies for taking so long to fix this
