### ISSUE TITLE
how to reproduce meep simulations from the examples?

### ISSUE THREAD

**Issue by joamatab** [DerekK88/PICwriter#23]
![image](https://user-images.githubusercontent.com/4514346/66420096-224a6300-e9ba-11e9-842c-19989b155f3a.png)

**Comment by joamatab** [comment]
file meep-sim-norm-res20.dat seems empty, how can we check the MPB and meep compatibility?

**Comment by DerekK88** [comment]
I was able to reproduce this issue on a system without parallel meep.  If the `parallel` argument is set to `True`, it will attempt to run with `mpirun`.  However, it will crash silently if you are just using serial meep.

If you'd like to run with [parallel meep](https://meep.readthedocs.io/en/latest/Installation/#official-releases), you can create a fresh conda env with the corresponding package:
`conda create -n pmp -c conda-forge pymeep=*=mpi_mpich_*`
or install into another existing environment:
`conda install -c condo-forge pymeep=*=mpi_mpich_*`

Otherwise, just setting the `parallel` argument to `False` should let it run.  I also changed the documentation (abcf2ce) so the example uses regular meep by default.
